# version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  items-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: items-api
    env_file:
    - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata:
